branch-defaults:
  master:
    environment: myImageProject-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: myImageProject
  branch: null
  default_ec2_keyname: practiceKey
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
